// <auto-generated />
using System;
using ContactManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactManagementSystem.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20210819014449_make phone nullable")]
    partial class makephonenullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ContactManagementSystem.Data.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cad74dc-70fa-4aa9-a697-9062e2474a59"),
                            BirthDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Johnson",
                            PhoneNumber = "555-555-5555"
                        },
                        new
                        {
                            Id = new Guid("0c4d0709-33eb-48b7-88b9-3d5989891f66"),
                            BirthDate = new DateTime(1975, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sherlock",
                            LastName = "Holmes",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("4997d69e-5e81-4847-b018-747d33d2ed15"),
                            BirthDate = new DateTime(1992, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            LastName = "Lee",
                            PhoneNumber = "248-867-5309"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
